- name: install OpenJDK 8, Maven, ...
  apt:
    pkg:
      - openjdk-8-jdk
      - maven
      - git
      - mc
    update_cache: yes

- name: Remove host name from /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: ^127\.0\.1\.1.*$

- name: Update the /etc/hosts file with host names
  lineinfile:
    path: /etc/hosts
    regexp: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
  with_items: "{{groups['all']}}"

- name: Create user "{{ uusername }}"
  user:
    name: "{{ uusername }}"
    shell: /bin/bash

- name: Enable access for local client ssh key
  authorized_key:
    user: "{{ uusername }}"
    state: present
    key: "{{ lookup('file', ssh_pub_key_path) }}"

