# - name: Download data
#   shell: >
#     source /home/{{uusername}}/.hadooprc &&
#     curl -sL https://snap.stanford.edu/data/bigdata/communities/com-friendster.ungraph.txt.gz |
#     gunzip |
#     hdfs dfs -put - /user/{{uusername}}/graph.txt
#   args: 
#     executable: /bin/bash

- name: Download Giraph
  shell: >
    cd {{service_dir}} &&
    git clone https://github.com/apache/giraph.git &&
    sed -i 's/3.0.0-SNAPSHOT/3.2.1/' giraph/pom.xml
  args:
    executable: /bin/bash

- name: Uploading test graph
  copy:
    src: tiny_graph.txt
    dest: /tmp/
    owner: '{{uusername}}'
    mode: '0644'

- name: Upload test graph to HDFS
  shell: >
    source /home/{{uusername}}/.hadooprc &&
    hdfs dfs -mkdir input &&
    hdfs dfs -copyFromLocal /tmp/tiny_graph.txt input/tiny_graph.txt
  args: 
    executable: /bin/bash

- name: Compiling Giraph
  shell: >
    source /home/{{uusername}}/.hadooprc &&
    cd {{service_dir}}/giraph &&
    mvn package -Phadoop_snapshot -DskipTests
  args: 
    executable: /bin/bash
  
  